
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: true,
    dataURL: 'https://weatherapi-com.p.rapidapi.com/forecast.json',
    xRapidAPIHostName: 'X-RapidAPI-Host',
    xRapidAPIHostValue: 'weatherapi-com.p.rapidapi.com',
    xRapidAPIKeyName: 'X-RapidAPI-Key',
    xRapidAPIKeyValue: 'e4bc16182fmsh24bbf52f40282b5p1ff76djsn2d42ff7b26ed'
  };
